language: node_js

node_js:
  - '12.16.1'

dist: trusty

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng build --prod --base-href https://oussamaMesseguem.github.io/nectar/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/nectar
  on:
    branch: master