language: node_js

node_js:
  - '12.16.1'

dist: trusty
sudo: false

branches:
  only:
  - master

notifications:
  email: false

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
- ng lint
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
- ng build --prod --base-href https://oussamaMesseguem.github.io/nectar/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/nectar
  on:
    branch: master