language: node_js

node_js:
  - '12.16.1'

dist: trusty
sudo: false

branches:
  only:
  - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
- ng build --prod --base-href https://oussamaMesseguem.github.io/nectar/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/nectar
  on:
    branch: master